<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BTG</name>
   <tag></tag>
   <elementGuidId>6b3ec5bc-d637-428b-8cd2-2ba23b9ae932</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class=&quot;css-1cfh8ii&quot;]//div[contains(text(),&quot;BTG&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class=&quot;css-1cfh8ii&quot;]//div[contains(text(),&quot;BTG&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
