<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LTC</name>
   <tag></tag>
   <elementGuidId>3aabba9c-bf0c-469e-81cf-bf9292ed2b47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class=&quot;css-1cfh8ii&quot;]//div[contains(text(),&quot;LTC&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class=&quot;css-1cfh8ii&quot;]//div[contains(text(),&quot;LTC&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
