<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Signout</name>
   <tag></tag>
   <elementGuidId>f58c42ba-94ad-4da0-a79a-efdd798046b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;deltix__app&quot;]/div/div[2]/div[1]/div[4]/div[@class=&quot;css-1c2xyfp&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;deltix__app&quot;]/div/div[2]/div[1]/div[4]/div[@class=&quot;css-1c2xyfp&quot;]</value>
   </webElementProperties>
</WebElementEntity>
