<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Fee</name>
   <tag></tag>
   <elementGuidId>9dff3b0d-e07b-4b21-99df-3beb39dfd112</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class=&quot;css-oat7h3&quot;]/div[3]/div[@class=&quot;css-1ng2vru&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class=&quot;css-oat7h3&quot;]/div[3]/div[@class=&quot;css-1ng2vru&quot;]</value>
   </webElementProperties>
</WebElementEntity>
